version: '3'
services:

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graf
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
       - phpmy

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
    networks:
      - phpmy

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - phpmy
networks:
  phpmy:
volumes:
  db_data: